name: Update Checker

on:
  workflow_dispatch:
  schedule:
    - cron: 0 * * * *

env:
  TZ: Asia/Shanghai

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
    - name: Get Kernel Version
      id: getKernel
      run: |
        git clone --depth 1 https://android.googlesource.com/kernel/common -b android12-5.10-lts ${GITHUB_WORKSPACE}/common
        cd ${GITHUB_WORKSPACE}/common
        VERSION=$(grep "^VERSION = .*$" Makefile | awk '{print $3}')
        PATCHLEVEL=$(grep "^PATCHLEVEL = .*$" Makefile | awk '{print $3}')
        SUBLEVEL=$(grep "^SUBLEVEL = .*$" Makefile | awk '{print $3}')
        Kernel_VER="android12-${VERSION}.${PATCHLEVEL}.${SUBLEVEL}"
        Kernel_HEAD=$(git rev-parse HEAD)
        echo "Kernel_VER=${Kernel_VER}" >> "$GITHUB_OUTPUT"
        echo "Kernel_HEAD=${Kernel_HEAD}" >> "$GITHUB_OUTPUT"

    - name: Get Version
      id: getVersion
      run: |
        kernel_h=$(curl -skL https://api.github.com/repos/hubbylei/AnyKernel-android12-5.10/releases/latest | jq -r .body | grep "Latest Kernel:" | awk '{print $4}' | sed 's,.*(\(.*\)),\1,')
        echo "Kernel_HEAD=${kernel_h}" >> "$GITHUB_OUTPUT"

    - name: Compare Version Version
      id: compare
      run: |
        if [ "${{ steps.getVersion.outputs.Kernel_HEAD }}" = "${{ steps.getKernel.outputs.Kernel_HEAD }}" ];then
          echo "build=false" >> "$GITHUB_OUTPUT"
        else
          echo "build=true" >> "$GITHUB_OUTPUT"
        fi

    - name: Auto compile
      if: steps.compare.outputs.build == 'true'
      uses: peter-evans/repository-dispatch@v3
      with:
        event-type: Auto compile

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 1
